### ISSUE TITLE
Contributors Page?

### ISSUE THREAD

**Issue by raghunayyar** [raghunayyar/devanagari-dictionary#2]
If someone contributes to dictionary successfully, should we add him to the list of contributors?

@girish-dalvi what do you think? do we need a dedicated page for it? If yes, @sitarashah @dil33pm.

**Comment by dil33pm** [comment]
Yes, I think it would be helpful to the visitors of the website to see who all contributed to which all. Can we put the Contributors list and their contributions under the page where they have contributed instead of a dedicated page? Like we put 'reference' when we use sources from the internet. If we can link the profiles of the contributors, interested people can contact them directly too.

**Comment by raghunayyar** [comment]
We have a contributors page now.
